# Generated by Django 5.1.2 on 2024-10-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_whatsapp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
