# Generated by Django 5.1.1 on 2024-10-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=0, upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
    ]
