# Generated by Django 5.1.1 on 2024-10-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_property_image_remove_property_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='address',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_meters',
        ),
        migrations.AddField(
            model_name='property',
            name='access',
            field=models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('difficult', 'Difícil')], default='easy', max_length=20, verbose_name='Acesso'),
        ),
        migrations.AddField(
            model_name='property',
            name='accessibility',
            field=models.BooleanField(default=False, verbose_name='Acessibilidade'),
        ),
        migrations.AddField(
            model_name='property',
            name='condo_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do condomínio'),
        ),
        migrations.AddField(
            model_name='property',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.CharField(default='Nenhum', max_length=255, verbose_name='Adereços'),
        ),
        migrations.AddField(
            model_name='property',
            name='free_spot',
            field=models.BooleanField(default=False, verbose_name='Vaga livre'),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_spots',
            field=models.IntegerField(default=0, verbose_name='Vagas de garagem'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_gatehouse',
            field=models.BooleanField(default=False, verbose_name='Portaria'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_pool',
            field=models.BooleanField(default=False, verbose_name='Piscina'),
        ),
        migrations.AddField(
            model_name='property',
            name='iptu_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do IPTU'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_covered',
            field=models.BooleanField(default=False, verbose_name='Cobertura'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='Alguém mora no imóvel'),
        ),
        migrations.AddField(
            model_name='property',
            name='move_availability',
            field=models.CharField(choices=[('immediate', 'Imediata'), ('30_days', '30 dias'), ('60_days', '60 dias'), ('other', 'Outro')], default='immediate', max_length=20, verbose_name='Disponibilidade de mudança'),
        ),
        migrations.AddField(
            model_name='property',
            name='owner_name',
            field=models.CharField(default='Não especificado', max_length=255, verbose_name='Nome completo do proprietário'),
        ),
        migrations.AddField(
            model_name='property',
            name='phone_number',
            field=models.CharField(default='(00) 00000-0000', max_length=15, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='property',
            name='private_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Área privativa (m²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_area',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Área útil do imóvel (m²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('commercial', 'Comercial')], default='apartment', max_length=50, verbose_name='Tipo de Imóvel'),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do aluguel'),
        ),
        migrations.AddField(
            model_name='property',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor de venda'),
        ),
        migrations.AddField(
            model_name='property',
            name='street',
            field=models.CharField(default='Não especificada', max_length=255, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='property',
            name='suites',
            field=models.IntegerField(default=0, verbose_name='Suítes'),
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(default='00000-000', max_length=10, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.IntegerField(default=1, verbose_name='Banheiros'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.IntegerField(default=1, verbose_name='Dormitórios (incluindo suítes)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(default='Não especificada', max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.CharField(default='Não especificado', max_length=100, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(default='Não especificado', max_length=100, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_number',
            field=models.CharField(default='0', max_length=10, verbose_name='Número'),
        ),
    ]
