# Generated by Django 5.1.1 on 2024-10-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_property_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='accessibility',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=3, verbose_name='Acessibilidade'),
        ),
        migrations.AlterField(
            model_name='property',
            name='free_spot',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=3, verbose_name='Vaga livre'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_gatehouse',
            field=models.CharField(choices=[('24h', '24 h'), ('daytime', 'Diurna'), ('night', 'Noturna'), ('none', 'Sem portaria')], default='none', max_length=20, verbose_name='Portaria'),
        ),
        migrations.AlterField(
            model_name='property',
            name='has_pool',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=3, verbose_name='Piscina'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_covered',
            field=models.CharField(choices=[('yes', 'Sim'), ('no', 'Não')], default='no', max_length=3, verbose_name='Cobertura'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_occupied',
            field=models.CharField(choices=[('vacant', 'Está vago'), ('owner', 'Proprietário mora'), ('tenant', 'Inquilino mora')], default='vacant', max_length=20, verbose_name='Alguém mora no imóvel'),
        ),
    ]
