# Generated by Django 5.1.1 on 2024-10-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_property_accessibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='free_spot',
        ),
        migrations.AddField(
            model_name='property',
            name='free_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição livre'),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_type',
            field=models.CharField(choices=[('covered', 'Coberta'), ('free', 'Livre'), ('covered_and_free', 'Coberta e Livre'), ('none', 'Nem Coberta nem Livre')], default='none', max_length=20, verbose_name='Tipo de Vaga'),
        ),
    ]
