# Generated by Django 5.1.1 on 2024-10-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_property_free_spot_property_free_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='access',
            field=models.CharField(choices=[('Key', 'Chave'), ('Biometry', 'Biometria'), ('Password', 'Senha')], default='Key', max_length=20, verbose_name='Acesso'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('land', 'lote'), ('farm', 'fazenda'), ('wahehouse', 'Galpão'), ('commercial', 'Comercial')], default='apartment', max_length=50, verbose_name='Tipo de Imóvel'),
        ),
    ]
