# Generated by Django 5.1.1 on 2024-10-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_property_access_alter_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL for the property video (e.g., YouTube link)', max_length=500, null=True),
        ),
    ]
