# Generated by Django 5.1.2 on 2024-10-14 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_property_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartamento'), ('house', 'Casa'), ('land', 'Lote'), ('farm', 'Fazenda'), ('wahehouse', 'Galpão'), ('commercial', 'Comercial')], default='apartment', max_length=50, verbose_name='Tipo de Imóvel'),
        ),
        migrations.AlterField(
            model_name='property',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do vídeo do imóvel (e.g., YouTube link)', max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Lance')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Lance')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='sales.property', verbose_name='Imóvel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_closed', models.DateTimeField(auto_now_add=True, verbose_name='Data de Fechamento')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('closed', 'Fechado')], max_length=50, verbose_name='Status')),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='sales.bid', verbose_name='Lance')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL, verbose_name='Comprador')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.property', verbose_name='Imóvel')),
            ],
        ),
    ]
