# Generated by Django 5.1.2 on 2024-10-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_property_owner_alter_property_property_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Condições de Pagamento'),
        ),
    ]
