# Generated by Django 5.1.2 on 2024-10-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_remove_property_email_remove_property_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyowner',
            name='is_married',
            field=models.CharField(choices=[('Yes', 'Sim'), ('No', 'Não')], default='No', max_length=3, verbose_name='É casado'),
        ),
    ]
