# Generated by Django 5.1.2 on 2024-10-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_propertyowner_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyowner',
            name='profile_picture',
        ),
    ]
