# Generated by Django 5.1.2 on 2024-10-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_remove_propertyowner_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyowner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='propertyowner',
            name='full_name',
        ),
    ]
