# Generated by Django 5.1.2 on 2024-10-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_propertyowner_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owners',
            new_name='owner',
        ),
    ]
