# Generated by Django 5.2 on 2025-04-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0018_dealstep_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="closed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fechado em"
            ),
        ),
        migrations.AddField(
            model_name="dealstep",
            name="comment",
            field=models.TextField(
                blank=True, null=True, verbose_name="Comentário da advogada"
            ),
        ),
    ]
